version: "3.8"

services:
  website:
    build:  .
    command:  >
      gunicorn -b 0.0.0.0:8000
              --access-logfile -
              --reload
              "snakeeyes.app:create_app()"
    environment:
      PYTHONUNBUFFERED: 'true'
    ports:
      - '8000:8000'
    working_dir: /snakeeyes
    volumes:
      - './:/snakeeyes'

